### PR TITLE
Support undefined typedef union

### LINKED ISSUE #214: Error on undefined typedef union
I have something like this in my C header (similar to #58):

```
typedef union secretunion SECRET;
```

When I try to wrap this, I actually get an error:

```
[ Info: Error thrown. Last cursor available in Clang.wrap_c.debug_cursors
ERROR: LoadError: BoundsError: attempt to access 0-element Array{Clang.cindex.CLCursor,1} at index [0]
Stacktrace:
 [1] getindex at ./array.jl:731 [inlined]
 [2] largestfield(::Clang.cindex.UnionDecl) at Clang/src/wrap_c.jl:312
 [...]
 [5] wrap(::Clang.wrap_c.WrapContext, ::OrderedCollections.OrderedDict{Symbol,Clang.wrap_c.ExprUnit}, ::Clang.cindex.UnionDecl) at Clang/src/wrap_c.jl:436
 [6] wrap_header(::Clang.wrap_c.WrapContext, ::Clang.cindex.TranslationUnit, ::String, ::Array{Any,1}) at Clang/src/wrap_c.jl:685
 [...]
```

The problem seems to be that `largestfield` tries to return access `fields[0]` while `fields` is actually empty:
```
function largestfield(cu::UnionDecl)
    maxsize,maxelem = 0,0
    fields = children(cu)
    for i in 1:length(fields)
        field_size = typesize(cu_type(fields[i]))
        if field_size > maxsize
            maxsize = field_size
            maxelem = i
        end
    end
    fields[maxelem]
end
```

### PR DESCRIPTION
**Pull request by leethargo**
This is an attempt to fix #214.

Unfortunately, the tests did not pass for me, so I did not add any for this case yet.

### CODE REVIEW

**Comment by leethargo** [comment]
FYI, this is what fails for me:
```[ Info: Error parsing function_default_arg value: -10)
function: Test Failed at /home/rs/.julia/dev/Clang/test/functions.jl:17
  Expression: defs == (nothing, -10)
   Evaluated: (Any[],) == (nothing, -10)
```

This is on Clang master with Julia 1.0.2.

**Comment by leethargo** [comment]
Right now, `typedef union uUnion UUNION` will generate this:

```
struct uUnion
    _uUnion::Cvoid
end

const UUNION = Cvoid
```

Here, `uUnion` is not correct, but at least `UUNION` is there.

**Comment by Gnimuc** [comment]
Fixed in #210, the result should be:
```julia
const uUnion = Cvoid
const UUNION = uUnion
```

**Comment by Gnimuc** [comment]
closed in favor of #216

**Pull request closed without merging**
