### PR TITLE
Rewrite wrapper to call libclang directly

### PR DESCRIPTION
**Pull request by ihnorton**
Tests pass, but still need to check on a few things.
Will make installation much simpler: no more compiling shim against libclang, only need libclang as a shared library.

### CODE REVIEW

**Comment by Gnimuc** [comment]
bump, any update plan for 1.0?

**Comment by ihnorton** [comment]
Getting closer. Passes tests for the libclang binding portion. wrap_c doesn't have very much coverage, so probably some work left there. I'll probably need to run some generators to shake that out.

**Comment by ihnorton** [comment]
@stemann thanks btw, I pulled those commits in to this branch.

**Comment by ihnorton** [comment]
Alright, tested on Sundials wrapper, and looks ok: runs all the way through, output has some differences but may be due to version bump or OS difference. I'm hoping to have time to dig a bit more and firm up the tests, but this is at least in the realm of usable now.

**Pull request merged**
